### PR TITLE
RFC: Fixes "Some sig durations are deleted during the preprocessing stage"

### PR DESCRIPTION
**Pull request by JDSanto**
New output:
```diff
In: "Take 1 tablet by mouth 3 times a day as needed for dizziness or nausea for up to 10 days."
Out:
(
    [sig_unit] => TAB
-   [sig_qty] => 270
-   [sig_days] => 90
+   [sig_qty] => 30
+   [sig_days] => 10
    [sig_conf_score] => 0.464563403216
    [frequencies] => 3
    [dosages] => 1
-   [durations] => 90
+   [durations] => 10
    [scores] => 0.517,0.998,0.964,0.934
-   [preprocessing] => Take 1 tablet by mouth 3 times a day as needed for dizziness or nausea for
+   [preprocessing] => Take 1 tablet by mouth 3 times a day as needed for dizziness or nausea for up to 10 days.
)
```
```diff
In: "Place 1 tablet under the tongue every 6  hours as needed for nausea or vomiting for up to 7 days."
Out:
(
    [sig_unit] => TAB
-   [sig_qty] => 360
-   [sig_days] => 90
+   [sig_qty] => 28
+   [sig_days] => 7
    [sig_conf_score] => 0.30454818696
    [frequencies] => 4
    [dosages] => 1
-   [durations] => 90
+   [durations] => 7
    [scores] => 0.552,0.999,0.615,0.898
-   [preprocessing] => Place 1 tablet under the tongue every 6 hours as needed for nausea or vomiting for
+   [preprocessing] => Place 1 tablet under the tongue every 6 hours as needed for nausea or vomiting for up to 7 days.
)
```

### CODE REVIEW

**Comment by gvillafanetapia** [comment]
Just so I understand.. what was it pre-processing it to before and what is the result now?

`Take 1 tablet by mouth 3 times a day as needed for dizziness or nausea for up to 10 days.` => ?

**Comment by gvillafanetapia** [comment]
sorry just saw it in the detail 🙃 

so basically by not erasing that in the end it works? 🤔

**Comment by gvillafanetapia** [comment]
I mean why was it like that before? I'm just afraid of regression errors.. because I see that you are going to be ignoring that delete after regex if days comes up

**Comment by JDSanto** [comment]
For the sigs we've checked, there's cases where it might include a maximum dosage at the end of it:
```
Take 1 capsule by mouth every 4 hours for a maximum of 8 capsules per day
```
The function `early_return()` already tries to handle cases in which the sig has a maximum dose, so at this point of the parsing we need to make sure the `maximum of 8 capsules per day` isn't treated as yet another dosage.

This maximum dosage was deleted in a very simple manner, checking expressions like `/ max/i`, `/ total of/i`, `/ up to/i` and so on. It needs to happen in the preprocessing stage because these keywords don't usually appear as AWS comprehend medical attributes.

However, for these couple of sigs it was removing the duration, so now we check if it contains a duration (which at the end of the preprocessing it should be transformed to simply `"day"`) before deleting it.

And we weren't picking these up while benchmarking the parser because the `sig_qty_per_day` is the same with or without this fix. I've run the parser yet again with the new changes and it appears to return the same results while at the same time fixing the sigs.

**Comment by gvillafanetapia** [comment]
So basically if whatever comes after the extra instructions is a duration we keep it (by finding day/s) and if not we discard it.. ?

**Comment by JDSanto** [comment]
Exactly

**Comment by gvillafanetapia** [comment]
maybe catch weeks also..? i don't think months will come up

**Comment by JDSanto** [comment]
The preprocessing stage already takes care of transforming weeks/months to days, but just in case I've added weeks to the regex

**Review by gvillafanetapia — APPROVED** [review]

**Pull request merged**
